// Disable all captions for figures.
:!figure-caption:

// Hightlight code source and add the line number
:source-highlighter: coderay
:coderay-linenums-mode: table

[[Introducing-the-Togaf-Architect-module]]

[[introducing-the-togaf-architect-module]]
= Introducing the Togaf Architect module

The Togaf Architect module is a Modelio extension dedicated to the modeling of Enterprise Architecture based on TOGAF Standards.

By providing a profile dedicated to Togaf modeling, the Togaf Architect module enables you to realize a complete landscape of a company’s information systems.

The Togaf Architect module provides the following functionalities:

* Landscape and modeling of enterprises and their information systems at business, architecture and technological levels.
* Modeling of business data.

*Note:* In order to get the most out of Togaf Architect, you must be familiar with Modelio. If this is not the case, have a look at the Modelio user guides and learn how to use our tool.

[[footer]]
