//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;choice maxOccurs="unbounded" minOccurs="0">
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}note"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}constraint"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}stereotype"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}tagged-value"/>
 * &lt;/choice>
 * &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="is-abstract" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="is-leaf" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="visibility">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="Public"/>
 * &lt;enumeration value="Protected"/>
 * &lt;enumeration value="Private"/>
 * &lt;enumeration value="Visibility_Undefined"/>
 * &lt;enumeration value="Package_Visibility"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="is-elementary" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "noteOrConstraintOrStereotype"
})
@XmlRootElement(name = "instance")
public class JaxbInstance implements IVisitorElement {
    
    @XmlAttribute(required = true)
    protected String name;

    
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String visibility;

    
    @XmlAttribute(name = "is-abstract")
    protected Boolean isAbstract;

    
    @XmlAttribute(name = "is-leaf")
    protected Boolean isLeaf;

    
    @XmlAttribute(name = "is-elementary")
    protected Boolean isElementary;

    
    @XmlElements({
    @XmlElement(name = "tagged-value", type = JaxbTaggedValue.class),
    @XmlElement(name = "stereotype", type = JaxbStereotype.class),
    @XmlElement(name = "constraint", type = JaxbConstraint.class),
    @XmlElement(name = "note", type = JaxbNote.class)
})
    protected List<Object> noteOrConstraintOrStereotype;

    /**
     * Gets the value of the noteOrConstraintOrStereotype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noteOrConstraintOrStereotype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getNoteOrConstraintOrStereotype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbTaggedValue }
     * {@link JaxbStereotype }
     * {@link JaxbConstraint }
     * {@link JaxbNote }
     */
    
    public List<Object> getNoteOrConstraintOrStereotype() {
        if (this.noteOrConstraintOrStereotype == null) {
            this.noteOrConstraintOrStereotype = new ArrayList<>();
        }
        return this.noteOrConstraintOrStereotype;
    }

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setName(final String value) {
        this.name = value;
    }

    /**
     * Gets the value of the isAbstract property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsAbstract() {
        return this.isAbstract;
    }

    /**
     * Sets the value of the isAbstract property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsAbstract(final Boolean value) {
        this.isAbstract = value;
    }

    /**
     * Gets the value of the isLeaf property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsLeaf() {
        return this.isLeaf;
    }

    /**
     * Sets the value of the isLeaf property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsLeaf(final Boolean value) {
        this.isLeaf = value;
    }

    /**
     * Gets the value of the visibility property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getVisibility() {
        return this.visibility;
    }

    /**
     * Sets the value of the visibility property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setVisibility(final String value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the isElementary property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsElementary() {
        return this.isElementary;
    }

    /**
     * Sets the value of the isElementary property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsElementary(final Boolean value) {
        this.isElementary = value;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitInstance(this);
    }

}
