//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;choice maxOccurs="unbounded" minOccurs="0">
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}class-type"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}stereotype"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}tagged-value"/>
 * &lt;/choice>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "classTypeOrStereotypeOrTaggedValue"
})
@XmlRootElement(name = "dependency")
public class JaxbDependency implements IVisitorElement {
    
    @XmlElements({
    @XmlElement(name = "class-type", type = JaxbClassType.class),
    @XmlElement(name = "tagged-value", type = JaxbTaggedValue.class),
    @XmlElement(name = "stereotype", type = JaxbStereotype.class)
})
    protected List<Object> classTypeOrStereotypeOrTaggedValue;

    /**
     * Gets the value of the classTypeOrStereotypeOrTaggedValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classTypeOrStereotypeOrTaggedValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getClassTypeOrStereotypeOrTaggedValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbClassType }
     * {@link JaxbTaggedValue }
     * {@link JaxbStereotype }
     */
    
    public List<Object> getClassTypeOrStereotypeOrTaggedValue() {
        if (this.classTypeOrStereotypeOrTaggedValue == null) {
            this.classTypeOrStereotypeOrTaggedValue = new ArrayList<>();
        }
        return this.classTypeOrStereotypeOrTaggedValue;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitDependency(this);
    }

}
