//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;choice maxOccurs="unbounded" minOccurs="0">
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}package"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}class"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}interface"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}enumeration"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}data-type"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}note"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}constraint"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}stereotype"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}tagged-value"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}generalization"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}use"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}element-import"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}package-import"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}realization"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}operation"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}association-end"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}attribute"/>
 * &lt;/choice>
 * &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "packageOrClazzOrInterface"
})
@XmlRootElement(name = "group")
public class JaxbGroup implements IVisitorElement {
    
    @XmlAttribute(required = true)
    protected String name;

    
    @XmlElements({
    @XmlElement(name = "data-type", type = JaxbDataType.class),
    @XmlElement(name = "element-import", type = JaxbElementImport.class),
    @XmlElement(name = "enumeration", type = JaxbEnumeration.class),
    @XmlElement(name = "package", type = JaxbPackage.class),
    @XmlElement(name = "association-end", type = JaxbAssociationEnd.class),
    @XmlElement(name = "class", type = JaxbClass.class),
    @XmlElement(name = "realization", type = JaxbRealization.class),
    @XmlElement(name = "interface", type = JaxbInterface.class),
    @XmlElement(name = "stereotype", type = JaxbStereotype.class),
    @XmlElement(name = "operation", type = JaxbOperation.class),
    @XmlElement(name = "note", type = JaxbNote.class),
    @XmlElement(name = "attribute", type = JaxbAttribute.class),
    @XmlElement(name = "constraint", type = JaxbConstraint.class),
    @XmlElement(name = "generalization", type = JaxbGeneralization.class),
    @XmlElement(name = "tagged-value", type = JaxbTaggedValue.class),
    @XmlElement(name = "package-import", type = JaxbPackageImport.class),
    @XmlElement(name = "use", type = JaxbUse.class)
})
    protected List<Object> packageOrClazzOrInterface;

    /**
     * Gets the value of the packageOrClazzOrInterface property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packageOrClazzOrInterface property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getPackageOrClazzOrInterface().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbDataType }
     * {@link JaxbElementImport }
     * {@link JaxbEnumeration }
     * {@link JaxbPackage }
     * {@link JaxbAssociationEnd }
     * {@link JaxbClass }
     * {@link JaxbRealization }
     * {@link JaxbInterface }
     * {@link JaxbStereotype }
     * {@link JaxbOperation }
     * {@link JaxbNote }
     * {@link JaxbAttribute }
     * {@link JaxbConstraint }
     * {@link JaxbGeneralization }
     * {@link JaxbTaggedValue }
     * {@link JaxbPackageImport }
     * {@link JaxbUse }
     */
    
    public List<Object> getPackageOrClazzOrInterface() {
        if (this.packageOrClazzOrInterface == null) {
            this.packageOrClazzOrInterface = new ArrayList<>();
        }
        return this.packageOrClazzOrInterface;
    }

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setName(final String value) {
        this.name = value;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitGroup(this);
    }

}
