//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}model"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}external-element" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}report-list"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "model",
    "externalElement",
    "reportList"
})
@XmlRootElement(name = "reversed-data")
public class JaxbReversedData implements IVisitorElement {
    
    @XmlElement(required = true)
    protected JaxbModel model;

    
    @XmlElement(name = "external-element")
    protected List<JaxbExternalElement> externalElement;

    
    @XmlElement(name = "report-list", required = true)
    protected JaxbReportList reportList;

    /**
     * Gets the value of the model property.
     * @return
     * possible object is
     * {@link JaxbModel }
     */
    
    public JaxbModel getModel() {
        return this.model;
    }

    /**
     * Sets the value of the model property.
     * @param value allowed object is
     * {@link JaxbModel }
     */
    
    public void setModel(final JaxbModel value) {
        this.model = value;
    }

    /**
     * Gets the value of the externalElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getExternalElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbExternalElement }
     */
    
    public List<JaxbExternalElement> getExternalElement() {
        if (this.externalElement == null) {
            this.externalElement = new ArrayList<>();
        }
        return this.externalElement;
    }

    /**
     * Gets the value of the reportList property.
     * @return
     * possible object is
     * {@link JaxbReportList }
     */
    
    public JaxbReportList getReportList() {
        return this.reportList;
    }

    /**
     * Sets the value of the reportList property.
     * @param value allowed object is
     * {@link JaxbReportList }
     */
    
    public void setReportList(final JaxbReportList value) {
        this.reportList = value;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitReversedData(this);
    }

}
