//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;simpleContent>
 * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 * &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/extension>
 * &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="metaclass" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "external-element")
public class JaxbExternalElement implements IVisitorElement {
    
    @XmlAttribute(name = "package")
    protected String _package;

    
    @XmlAttribute(name = "class")
    protected String clazz;

    
    @XmlAttribute(name = "metaclass")
    protected String metaclass;

    
    @XmlValue
    protected String value;

    
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the package property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getPackage() {
        return this._package;
    }

    /**
     * Sets the value of the package property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setPackage(final String value) {
        this._package = value;
    }

    /**
     * Gets the value of the clazz property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getClazz() {
        return this.clazz;
    }

    /**
     * Sets the value of the clazz property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setClazz(final String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the metaclass property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getMetaclass() {
        return this.metaclass;
    }

    /**
     * Sets the value of the clazz property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setMetaClass(final String value) {
        this.metaclass = value;
    }

    /**
     * Gets the value of the value property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getValue() {
        return this.value;
    }

    /**
     * Sets the value of the value property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setValue(final String value) {
        this.value = value;
    }

    /**
     * Gets the value of the id property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of the id property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setId(final String value) {
        this.id = value;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitExternalElement(this);
    }

}
