//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;choice maxOccurs="unbounded" minOccurs="0">
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}operation-representation"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}note"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}constraint"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}stereotype"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}tagged-value"/>
 * &lt;/choice>
 * &lt;attribute name="visibility">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="Public"/>
 * &lt;enumeration value="Protected"/>
 * &lt;enumeration value="Private"/>
 * &lt;enumeration value="Visibility_Undefined"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="is-class" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="refid" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="objid" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operationRepresentationOrNoteOrConstraint"
})
@XmlRootElement(name = "signal")
public class JaxbSignal implements IVisitorElement {
    
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String visibility;

    
    @XmlAttribute
    protected String name;

    
    @XmlAttribute
    protected String id;

    
    @XmlAttribute
    protected String objid;

    
    @XmlAttribute(name = "is-class")
    protected Boolean isClass;

    
    @XmlAttribute
    protected String refid;

    
    @XmlElements({
    @XmlElement(name = "tagged-value", type = JaxbTaggedValue.class),
    @XmlElement(name = "constraint", type = JaxbConstraint.class),
    @XmlElement(name = "operation-representation", type = JaxbOperationRepresentation.class),
    @XmlElement(name = "stereotype", type = JaxbStereotype.class),
    @XmlElement(name = "note", type = JaxbNote.class)
})
    protected List<Object> operationRepresentationOrNoteOrConstraint;

    /**
     * Gets the value of the operationRepresentationOrNoteOrConstraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operationRepresentationOrNoteOrConstraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getOperationRepresentationOrNoteOrConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbTaggedValue }
     * {@link JaxbConstraint }
     * {@link JaxbOperationRepresentation }
     * {@link JaxbStereotype }
     * {@link JaxbNote }
     */
    
    public List<Object> getOperationRepresentationOrNoteOrConstraint() {
        if (this.operationRepresentationOrNoteOrConstraint == null) {
            this.operationRepresentationOrNoteOrConstraint = new ArrayList<>();
        }
        return this.operationRepresentationOrNoteOrConstraint;
    }

    /**
     * Gets the value of the visibility property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getVisibility() {
        return this.visibility;
    }

    /**
     * Sets the value of the visibility property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setVisibility(final String value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the isClass property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsClass() {
        return this.isClass;
    }

    /**
     * Sets the value of the isClass property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsClass(final Boolean value) {
        this.isClass = value;
    }

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setName(final String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of the id property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setId(final String value) {
        this.id = value;
    }

    /**
     * Gets the value of the objid property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getObjid() {
        return this.objid;
    }

    /**
     * Sets the value of the objid property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setObjid(final String value) {
        this.objid = value;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitSignal(this);
    }

    /**
     * Gets the value of the refid property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getRefid() {
        return this.refid;
    }

    /**
     * Sets the value of the refid property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setRefid(final String value) {
        this.refid = value;
    }

}
