//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}title"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}target-item" minOccurs="0"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}report"/>
 * &lt;/sequence>
 * &lt;attribute name="type" use="required">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="info"/>
 * &lt;enumeration value="warning"/>
 * &lt;enumeration value="error"/>
 * &lt;enumeration value="modification"/>
 * &lt;enumeration value="addition"/>
 * &lt;enumeration value="deletion"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "targetItem",
    "report"
})
@XmlRootElement(name = "report-item")
public class JaxbReportItem implements IVisitorElement {
    
    @XmlElement(required = true)
    protected String title;

    
    @XmlElement(required = true)
    protected String report;

    
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;

    
    @XmlElement(name = "target-item")
    protected JaxbTargetItem targetItem;

    /**
     * Gets the value of the title property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getTitle() {
        return this.title;
    }

    /**
     * Sets the value of the title property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setTitle(final String value) {
        this.title = value;
    }

    /**
     * Gets the value of the targetItem property.
     * @return
     * possible object is
     * {@link JaxbTargetItem }
     */
    
    public JaxbTargetItem getTargetItem() {
        return this.targetItem;
    }

    /**
     * Sets the value of the targetItem property.
     * @param value allowed object is
     * {@link JaxbTargetItem }
     */
    
    public void setTargetItem(final JaxbTargetItem value) {
        this.targetItem = value;
    }

    /**
     * Gets the value of the report property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getReport() {
        return this.report;
    }

    /**
     * Sets the value of the report property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setReport(final String value) {
        this.report = value;
    }

    /**
     * Gets the value of the type property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getType() {
        return this.type;
    }

    /**
     * Sets the value of the type property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setType(final String value) {
        this.type = value;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitReportItem(this);
    }

}
