//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;choice maxOccurs="unbounded" minOccurs="0">
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}parameter"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}template-parameter"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}return-parameter"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}use"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}element-import"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}package-import"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}raised-exception"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}note"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}constraint"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}stereotype"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}tagged-value"/>
 * &lt;/choice>
 * &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="passing">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="MethodIn"/>
 * &lt;enumeration value="MethodOut"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="final" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="concurrency" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="is-abstract" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="is-class" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="visibility">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="Public"/>
 * &lt;enumeration value="Protected"/>
 * &lt;enumeration value="Private"/>
 * &lt;enumeration value="Visibility_Undefined"/>
 * &lt;enumeration value="Package_Visibility"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="refid" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="objid" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parameterOrTemplateParameterOrReturnParameter"
})
@XmlRootElement(name = "operation")
public class JaxbOperation implements IVisitorElement {
    
    @XmlAttribute(required = true)
    protected String name;

    
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String passing;

    
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String visibility;

    
    @XmlAttribute
    protected String id;

    
    @XmlAttribute
    protected String objid;

    
    @XmlAttribute(name = "final")
    protected Boolean _final;

    
    @XmlAttribute
    protected Boolean concurrency;

    
    @XmlAttribute(name = "is-abstract")
    protected Boolean isAbstract;

    
    @XmlAttribute(name = "is-class")
    protected Boolean isClass;

    
    @XmlAttribute
    protected String refid;

    
    @XmlElements({
    @XmlElement(name = "raised-exception", type = JaxbRaisedException.class),
    @XmlElement(name = "template-parameter", type = JaxbTemplateParameter.class),
    @XmlElement(name = "note", type = JaxbNote.class),
    @XmlElement(name = "element-import", type = JaxbElementImport.class),
    @XmlElement(name = "tagged-value", type = JaxbTaggedValue.class),
    @XmlElement(name = "constraint", type = JaxbConstraint.class),
    @XmlElement(name = "return-parameter", type = JaxbReturnParameter.class),
    @XmlElement(name = "package-import", type = JaxbPackageImport.class),
    @XmlElement(name = "use", type = JaxbUse.class),
    @XmlElement(name = "parameter", type = JaxbParameter.class),
    @XmlElement(name = "stereotype", type = JaxbStereotype.class)
})
    protected List<Object> parameterOrTemplateParameterOrReturnParameter;

    /**
     * Gets the value of the parameterOrTemplateParameterOrReturnParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameterOrTemplateParameterOrReturnParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getParameterOrTemplateParameterOrReturnParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbRaisedException }
     * {@link JaxbTemplateParameter }
     * {@link JaxbNote }
     * {@link JaxbElementImport }
     * {@link JaxbTaggedValue }
     * {@link JaxbConstraint }
     * {@link JaxbReturnParameter }
     * {@link JaxbPackageImport }
     * {@link JaxbUse }
     * {@link JaxbParameter }
     * {@link JaxbStereotype }
     */
    
    public List<Object> getParameterOrTemplateParameterOrReturnParameter() {
        if (this.parameterOrTemplateParameterOrReturnParameter == null) {
            this.parameterOrTemplateParameterOrReturnParameter = new ArrayList<>();
        }
        return this.parameterOrTemplateParameterOrReturnParameter;
    }

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setName(final String value) {
        this.name = value;
    }

    /**
     * Gets the value of the passing property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getPassing() {
        return this.passing;
    }

    /**
     * Sets the value of the passing property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setPassing(final String value) {
        this.passing = value;
    }

    /**
     * Gets the value of the final property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isFinal() {
        return this._final;
    }

    /**
     * Sets the value of the final property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setFinal(final Boolean value) {
        this._final = value;
    }

    /**
     * Gets the value of the concurrency property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isConcurrency() {
        return this.concurrency;
    }

    /**
     * Sets the value of the concurrency property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setConcurrency(final Boolean value) {
        this.concurrency = value;
    }

    /**
     * Gets the value of the isAbstract property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsAbstract() {
        return this.isAbstract;
    }

    /**
     * Sets the value of the isAbstract property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsAbstract(final Boolean value) {
        this.isAbstract = value;
    }

    /**
     * Gets the value of the isClass property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsClass() {
        return this.isClass;
    }

    /**
     * Sets the value of the isClass property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsClass(final Boolean value) {
        this.isClass = value;
    }

    /**
     * Gets the value of the visibility property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getVisibility() {
        return this.visibility;
    }

    /**
     * Sets the value of the visibility property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setVisibility(final String value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the id property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of the id property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setId(final String value) {
        this.id = value;
    }

    /**
     * Gets the value of the objid property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getObjid() {
        return this.objid;
    }

    /**
     * Sets the value of the objid property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setObjid(final String value) {
        this.objid = value;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitOperation(this);
    }

    /**
     * Gets the value of the refid property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getRefid() {
        return this.refid;
    }

    /**
     * Sets the value of the refid property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setRefid(final String value) {
        this.refid = value;
    }

}
