//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.07.13 at 10:43:09 AM CEST
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.modeliosoft.com/rev-modele.xsd", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)

package org.modelio.module.javadesigner.xmlreverse.model;


