//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;choice maxOccurs="unbounded" minOccurs="0">
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}value"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}base-type"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}class-type"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}note"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}constraint"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}stereotype"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}tagged-value"/>
 * &lt;/choice>
 * &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="is-derived" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="is-set" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="multiplicity" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="type-constraint" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="changeable">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="Read"/>
 * &lt;enumeration value="Write"/>
 * &lt;enumeration value="ReadWrite"/>
 * &lt;enumeration value="AccessNone"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="target-is-class" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="is-abstract" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="is-class" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="visibility">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="Public"/>
 * &lt;enumeration value="Protected"/>
 * &lt;enumeration value="Private"/>
 * &lt;enumeration value="Visibility_Undefined"/>
 * &lt;enumeration value="Package_Visibility"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="refid" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="objid" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "valueOrBaseTypeOrClassType"
})
@XmlRootElement(name = "attribute")
public class JaxbAttribute implements IVisitorElement {
    
    @XmlAttribute(required = true)
    protected String name;

    
    @XmlAttribute
    protected String multiplicity;

    
    @XmlAttribute(name = "type-constraint")
    protected String typeConstraint;

    
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String changeable;

    
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String visibility;

    
    @XmlAttribute
    protected String id;

    
    @XmlAttribute
    protected String objid;

    
    @XmlAttribute(name = "is-derived")
    protected Boolean isDerived;

    
    @XmlAttribute(name = "is-set")
    protected Boolean isSet;

    
    @XmlAttribute(name = "target-is-class")
    protected Boolean targetIsClass;

    
    @XmlAttribute(name = "is-abstract")
    protected Boolean isAbstract;

    
    @XmlAttribute(name = "is-class")
    protected Boolean isClass;

    
    @XmlAttribute
    protected String refid;

    
    @XmlElementRefs({
    @XmlElementRef(name = "base-type", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JAXBElement.class),
    @XmlElementRef(name = "stereotype", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JaxbStereotype.class),
    @XmlElementRef(name = "constraint", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JaxbConstraint.class),
    @XmlElementRef(name = "value", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JAXBElement.class),
    @XmlElementRef(name = "tagged-value", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JaxbTaggedValue.class),
    @XmlElementRef(name = "class-type", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JaxbClassType.class),
    @XmlElementRef(name = "note", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JaxbNote.class)
})
    protected List<Object> valueOrBaseTypeOrClassType;

    /**
     * Gets the value of the valueOrBaseTypeOrClassType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valueOrBaseTypeOrClassType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getValueOrBaseTypeOrClassType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JaxbStereotype }
     * {@link JaxbConstraint }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JaxbTaggedValue }
     * {@link JaxbClassType }
     * {@link JaxbNote }
     */
    
    public List<Object> getValueOrBaseTypeOrClassType() {
        if (this.valueOrBaseTypeOrClassType == null) {
            this.valueOrBaseTypeOrClassType = new ArrayList<>();
        }
        return this.valueOrBaseTypeOrClassType;
    }

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setName(final String value) {
        this.name = value;
    }

    /**
     * Gets the value of the isDerived property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsDerived() {
        return this.isDerived;
    }

    /**
     * Sets the value of the isDerived property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsDerived(final Boolean value) {
        this.isDerived = value;
    }

    /**
     * Gets the value of the isSet property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsSet() {
        return this.isSet;
    }

    /**
     * Sets the value of the isSet property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsSet(final Boolean value) {
        this.isSet = value;
    }

    /**
     * Gets the value of the multiplicity property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getMultiplicity() {
        return this.multiplicity;
    }

    /**
     * Sets the value of the multiplicity property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setMultiplicity(final String value) {
        this.multiplicity = value;
    }

    /**
     * Gets the value of the typeConstraint property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getTypeConstraint() {
        return this.typeConstraint;
    }

    /**
     * Sets the value of the typeConstraint property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setTypeConstraint(final String value) {
        this.typeConstraint = value;
    }

    /**
     * Gets the value of the changeable property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getChangeable() {
        return this.changeable;
    }

    /**
     * Sets the value of the changeable property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setChangeable(final String value) {
        this.changeable = value;
    }

    /**
     * Gets the value of the targetIsClass property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isTargetIsClass() {
        return this.targetIsClass;
    }

    /**
     * Sets the value of the targetIsClass property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setTargetIsClass(final Boolean value) {
        this.targetIsClass = value;
    }

    /**
     * Gets the value of the isAbstract property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsAbstract() {
        return this.isAbstract;
    }

    /**
     * Sets the value of the isAbstract property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsAbstract(final Boolean value) {
        this.isAbstract = value;
    }

    /**
     * Gets the value of the isClass property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsClass() {
        return this.isClass;
    }

    /**
     * Sets the value of the isClass property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsClass(final Boolean value) {
        this.isClass = value;
    }

    /**
     * Gets the value of the visibility property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getVisibility() {
        return this.visibility;
    }

    /**
     * Sets the value of the visibility property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setVisibility(final String value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the id property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of the id property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setId(final String value) {
        this.id = value;
    }

    /**
     * Gets the value of the objid property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getObjid() {
        return this.objid;
    }

    /**
     * Sets the value of the objid property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setObjid(final String value) {
        this.objid = value;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitAttribute(this);
    }

    /**
     * Gets the value of the refid property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getRefid() {
        return this.refid;
    }

    /**
     * Sets the value of the refid property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setRefid(final String value) {
        this.refid = value;
    }

}
