//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.modelio.module.javadesigner.xmlreverse.model package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */

@XmlRegistry
public class ObjectFactory {
    
    private static final QName _Title_QNAME = new QName("http://www.modeliosoft.com/rev-modele.xsd", "title");

    
    private static final QName _Icon_QNAME = new QName("http://www.modeliosoft.com/rev-modele.xsd", "icon");

    
    private static final QName _Content_QNAME = new QName("http://www.modeliosoft.com/rev-modele.xsd", "content");

    
    private static final QName _TagParameter_QNAME = new QName("http://www.modeliosoft.com/rev-modele.xsd", "tag-parameter");

    
    private static final QName _IsInstantiable_QNAME = new QName("http://www.modeliosoft.com/rev-modele.xsd", "is-instantiable");

    
    private static final QName _DefaultValue_QNAME = new QName("http://www.modeliosoft.com/rev-modele.xsd", "default-value");

    
    private static final QName _BaseType_QNAME = new QName("http://www.modeliosoft.com/rev-modele.xsd", "base-type");

    
    private static final QName _Report_QNAME = new QName("http://www.modeliosoft.com/rev-modele.xsd", "report");

    
    private static final QName _Value_QNAME = new QName("http://www.modeliosoft.com/rev-modele.xsd", "value");

    
    private static final QName _PassingMode_QNAME = new QName("http://www.modeliosoft.com/rev-modele.xsd", "passing-mode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.modelio.module.javadesigner.xmlreverse.model
     */
    
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JaxbUsedPackage }
     */
    
    public JaxbUsedPackage createUsedPackage() {
        return new JaxbUsedPackage();
    }

    /**
     * Create an instance of {@link JaxbClass }
     */
    
    public JaxbClass createClass() {
        return new JaxbClass();
    }

    /**
     * Create an instance of {@link JaxbTemplateBinding }
     */
    
    public JaxbTemplateBinding createTemplateBinding() {
        return new JaxbTemplateBinding();
    }

    /**
     * Create an instance of {@link JaxbUse }
     */
    
    public JaxbUse createUse() {
        return new JaxbUse();
    }

    /**
     * Create an instance of {@link JaxbTemplateParameterSubstitution }
     */
    
    public JaxbTemplateParameterSubstitution createTemplateParameterSubstitution() {
        return new JaxbTemplateParameterSubstitution();
    }

    /**
     * Create an instance of {@link JaxbTaggedValue }
     */
    
    public JaxbTaggedValue createTaggedValue() {
        return new JaxbTaggedValue();
    }

    /**
     * Create an instance of {@link JaxbOperationRepresentation }
     */
    
    public JaxbOperationRepresentation createOperationRepresentation() {
        return new JaxbOperationRepresentation();
    }

    /**
     * Create an instance of {@link JaxbEnumerationLiteral }
     */
    
    public JaxbEnumerationLiteral createEnumerationLiteral() {
        return new JaxbEnumerationLiteral();
    }

    /**
     * Create an instance of {@link JaxbNote }
     */
    
    public JaxbNote createNote() {
        return new JaxbNote();
    }

    /**
     * Create an instance of {@link JaxbInstance }
     */
    
    public JaxbInstance createInstance() {
        return new JaxbInstance();
    }

    /**
     * Create an instance of {@link JaxbTargetItem }
     */
    
    public JaxbTargetItem createTargetItem() {
        return new JaxbTargetItem();
    }

    /**
     * Create an instance of {@link JaxbInterface }
     */
    
    public JaxbInterface createInterface() {
        return new JaxbInterface();
    }

    /**
     * Create an instance of {@link JaxbElementImport }
     */
    
    public JaxbElementImport createElementImport() {
        return new JaxbElementImport();
    }

    /**
     * Create an instance of {@link JaxbAttribute }
     */
    
    public JaxbAttribute createAttribute() {
        return new JaxbAttribute();
    }

    /**
     * Create an instance of {@link JaxbPackage }
     */
    
    public JaxbPackage createPackage() {
        return new JaxbPackage();
    }

    /**
     * Create an instance of {@link JaxbModel }
     */
    
    public JaxbModel createModel() {
        return new JaxbModel();
    }

    /**
     * Create an instance of {@link JaxbSuperType }
     */
    
    public JaxbSuperType createSuperType() {
        return new JaxbSuperType();
    }

    /**
     * Create an instance of {@link JaxbEnumeration }
     */
    
    public JaxbEnumeration createEnumeration() {
        return new JaxbEnumeration();
    }

    /**
     * Create an instance of {@link JaxbGroup }
     */
    
    public JaxbGroup createGroup() {
        return new JaxbGroup();
    }

    /**
     * Create an instance of {@link JaxbReportList }
     */
    
    public JaxbReportList createReportList() {
        return new JaxbReportList();
    }

    /**
     * Create an instance of {@link JaxbRealization }
     */
    
    public JaxbRealization createRealization() {
        return new JaxbRealization();
    }

    /**
     * Create an instance of {@link JaxbConstraint }
     */
    
    public JaxbConstraint createConstraint() {
        return new JaxbConstraint();
    }

    /**
     * Create an instance of {@link JaxbExternalElement }
     */
    
    public JaxbExternalElement createExternalElement() {
        return new JaxbExternalElement();
    }

    /**
     * Create an instance of {@link JaxbType }
     */
    
    public JaxbType createType() {
        return new JaxbType();
    }

    /**
     * Create an instance of {@link JaxbImplementedClass }
     */
    
    public JaxbImplementedClass createImplementedClass() {
        return new JaxbImplementedClass();
    }

    /**
     * Create an instance of {@link JaxbReturnParameter }
     */
    
    public JaxbReturnParameter createReturnParameter() {
        return new JaxbReturnParameter();
    }

    /**
     * Create an instance of {@link JaxbDataType }
     */
    
    public JaxbDataType createDataType() {
        return new JaxbDataType();
    }

    /**
     * Create an instance of {@link JaxbGeneralization }
     */
    
    public JaxbGeneralization createGeneralization() {
        return new JaxbGeneralization();
    }

    /**
     * Create an instance of {@link JaxbDependency }
     */
    
    public JaxbDependency createDependency() {
        return new JaxbDependency();
    }

    /**
     * Create an instance of {@link JaxbClassType }
     */
    
    public JaxbClassType createClassType() {
        return new JaxbClassType();
    }

    /**
     * Create an instance of {@link JaxbDir }
     */
    
    public JaxbDir createDir() {
        return new JaxbDir();
    }

    /**
     * Create an instance of {@link JaxbSignal }
     */
    
    public JaxbSignal createSignal() {
        return new JaxbSignal();
    }

    /**
     * Create an instance of {@link JaxbDefaultType }
     */
    
    public JaxbDefaultType createDefaultType() {
        return new JaxbDefaultType();
    }

    /**
     * Create an instance of {@link JaxbRaisedException }
     */
    
    public JaxbRaisedException createRaisedException() {
        return new JaxbRaisedException();
    }

    /**
     * Create an instance of {@link JaxbReversedData }
     */
    
    public JaxbReversedData createReversedData() {
        return new JaxbReversedData();
    }

    /**
     * Create an instance of {@link JaxbReportItem }
     */
    
    public JaxbReportItem createReportItem() {
        return new JaxbReportItem();
    }

    /**
     * Create an instance of {@link JaxbParameter }
     */
    
    public JaxbParameter createParameter() {
        return new JaxbParameter();
    }

    /**
     * Create an instance of {@link JaxbAssociationEnd }
     */
    
    public JaxbAssociationEnd createAssociationEnd() {
        return new JaxbAssociationEnd();
    }

    /**
     * Create an instance of {@link JaxbStereotype }
     */
    
    public JaxbStereotype createStereotype() {
        return new JaxbStereotype();
    }

    /**
     * Create an instance of {@link JaxbUsedClass }
     */
    
    public JaxbUsedClass createUsedClass() {
        return new JaxbUsedClass();
    }

    /**
     * Create an instance of {@link JaxbDestination }
     */
    
    public JaxbDestination createDestination() {
        return new JaxbDestination();
    }

    /**
     * Create an instance of {@link JaxbOperation }
     */
    
    public JaxbOperation createOperation() {
        return new JaxbOperation();
    }

    /**
     * Create an instance of {@link JaxbPackageImport }
     */
    
    public JaxbPackageImport createPackageImport() {
        return new JaxbPackageImport();
    }

    /**
     * Create an instance of {@link JaxbTemplateParameter }
     */
    
    public JaxbTemplateParameter createTemplateParameter() {
        return new JaxbTemplateParameter();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    
    @XmlElementDecl(namespace = "http://www.modeliosoft.com/rev-modele.xsd", name = "title")
    public JAXBElement<String> createTitle(final String value) {
        return new JAXBElement<>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    
    @XmlElementDecl(namespace = "http://www.modeliosoft.com/rev-modele.xsd", name = "icon")
    public JAXBElement<String> createIcon(final String value) {
        return new JAXBElement<>(_Icon_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    
    @XmlElementDecl(namespace = "http://www.modeliosoft.com/rev-modele.xsd", name = "content")
    public JAXBElement<String> createContent(final String value) {
        return new JAXBElement<>(_Content_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    
    @XmlElementDecl(namespace = "http://www.modeliosoft.com/rev-modele.xsd", name = "tag-parameter")
    public JAXBElement<String> createTagParameter(final String value) {
        return new JAXBElement<>(_TagParameter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    
    @XmlElementDecl(namespace = "http://www.modeliosoft.com/rev-modele.xsd", name = "is-instantiable")
    public JAXBElement<String> createIsInstantiable(final String value) {
        return new JAXBElement<>(_IsInstantiable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    
    @XmlElementDecl(namespace = "http://www.modeliosoft.com/rev-modele.xsd", name = "default-value")
    public JAXBElement<String> createDefaultValue(final String value) {
        return new JAXBElement<>(_DefaultValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    
    @XmlElementDecl(namespace = "http://www.modeliosoft.com/rev-modele.xsd", name = "base-type")
    public JAXBElement<String> createBaseType(final String value) {
        return new JAXBElement<>(_BaseType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    
    @XmlElementDecl(namespace = "http://www.modeliosoft.com/rev-modele.xsd", name = "report")
    public JAXBElement<String> createReport(final String value) {
        return new JAXBElement<>(_Report_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    
    @XmlElementDecl(namespace = "http://www.modeliosoft.com/rev-modele.xsd", name = "value")
    public JAXBElement<String> createValue(final String value) {
        return new JAXBElement<>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    
    @XmlElementDecl(namespace = "http://www.modeliosoft.com/rev-modele.xsd", name = "passing-mode")
    public JAXBElement<String> createPassingMode(final String value) {
        return new JAXBElement<>(_PassingMode_QNAME, String.class, null, value);
    }

}
