//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;choice maxOccurs="unbounded" minOccurs="0">
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}base-type"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}class-type"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}note"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}constraint"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}stereotype"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}tagged-value"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}default-value"/>
 * &lt;/choice>
 * &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="passing-mode">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="In"/>
 * &lt;enumeration value="Out"/>
 * &lt;enumeration value="Inout"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="is-set" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="multiplicity" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="type-constraint" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "baseTypeOrClassTypeOrNote"
})
@XmlRootElement(name = "parameter")
public class JaxbParameter implements IVisitorElement {
    
    @XmlAttribute(required = true)
    protected String name;

    
    @XmlAttribute(name = "passing-mode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String passingMode;

    
    @XmlAttribute
    protected String multiplicity;

    
    @XmlAttribute(name = "type-constraint")
    protected String typeConstraint;

    
    @XmlAttribute(name = "is-set")
    protected Boolean isSet;

    
    @XmlElementRefs({
    @XmlElementRef(name = "base-type", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JAXBElement.class),
    @XmlElementRef(name = "stereotype", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JaxbStereotype.class),
    @XmlElementRef(name = "constraint", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JaxbConstraint.class),
    @XmlElementRef(name = "class-type", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JaxbClassType.class),
    @XmlElementRef(name = "tagged-value", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JaxbTaggedValue.class),
    @XmlElementRef(name = "note", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JaxbNote.class),
    @XmlElementRef(name = "default-value", namespace = "http://www.modeliosoft.com/rev-modele.xsd", type = JAXBElement.class)
})
    protected List<Object> baseTypeOrClassTypeOrNote;

    /**
     * Gets the value of the baseTypeOrClassTypeOrNote property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baseTypeOrClassTypeOrNote property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getBaseTypeOrClassTypeOrNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JaxbStereotype }
     * {@link JaxbConstraint }
     * {@link JaxbClassType }
     * {@link JaxbTaggedValue }
     * {@link JaxbNote }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    
    public List<Object> getBaseTypeOrClassTypeOrNote() {
        if (this.baseTypeOrClassTypeOrNote == null) {
            this.baseTypeOrClassTypeOrNote = new ArrayList<>();
        }
        return this.baseTypeOrClassTypeOrNote;
    }

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setName(final String value) {
        this.name = value;
    }

    /**
     * Gets the value of the passingMode property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getPassingMode() {
        return this.passingMode;
    }

    /**
     * Sets the value of the passingMode property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setPassingMode(final String value) {
        this.passingMode = value;
    }

    /**
     * Gets the value of the isSet property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsSet() {
        return this.isSet;
    }

    /**
     * Sets the value of the isSet property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsSet(final Boolean value) {
        this.isSet = value;
    }

    /**
     * Gets the value of the multiplicity property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getMultiplicity() {
        return this.multiplicity;
    }

    /**
     * Sets the value of the multiplicity property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setMultiplicity(final String value) {
        this.multiplicity = value;
    }

    /**
     * Gets the value of the typeConstraint property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getTypeConstraint() {
        return this.typeConstraint;
    }

    /**
     * Sets the value of the typeConstraint property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setTypeConstraint(final String value) {
        this.typeConstraint = value;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitParameter(this);
    }

}
