//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;choice>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}class-type"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}base-type"/>
 * &lt;/choice>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "classType",
    "baseType"
})
@XmlRootElement(name = "default-type")
public class JaxbDefaultType implements IVisitorElement {
    
    @XmlElement(name = "base-type")
    protected String baseType;

    
    @XmlElement(name = "class-type")
    protected JaxbClassType classType;

    /**
     * Gets the value of the classType property.
     * @return
     * possible object is
     * {@link JaxbClassType }
     */
    
    public JaxbClassType getClassType() {
        return this.classType;
    }

    /**
     * Sets the value of the classType property.
     * @param value allowed object is
     * {@link JaxbClassType }
     */
    
    public void setClassType(final JaxbClassType value) {
        this.classType = value;
    }

    /**
     * Gets the value of the baseType property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getBaseType() {
        return this.baseType;
    }

    /**
     * Sets the value of the baseType property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setBaseType(final String value) {
        this.baseType = value;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitDefaultType(this);
    }

}
