//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;choice maxOccurs="unbounded" minOccurs="0">
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}class"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}interface"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}instance"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}signal"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}data-type"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}enumeration"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}template-parameter"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}generalization"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}use"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}element-import"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}package-import"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}realization"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}operation"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}attribute"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}association-end"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}note"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}constraint"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}stereotype"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}tagged-value"/>
 * &lt;/choice>
 * &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="is-main" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="is-active" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="is-abstract" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="is-leaf" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="visibility">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="Public"/>
 * &lt;enumeration value="Protected"/>
 * &lt;enumeration value="Private"/>
 * &lt;enumeration value="Visibility_Undefined"/>
 * &lt;enumeration value="Package_Visibility"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="is-elementary" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 * &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="refid" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="objid" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clazzOrInterfaceOrInstance"
})
@XmlRootElement(name = "class")
public class JaxbClass implements IVisitorElement {
    
    @XmlAttribute(required = true)
    protected String name;

    
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String visibility;

    
    @XmlAttribute
    protected String id;

    
    @XmlAttribute
    protected String objid;

    
    @XmlAttribute(name = "is-main")
    protected Boolean isMain;

    
    @XmlAttribute(name = "is-active")
    protected Boolean isActive;

    
    @XmlAttribute(name = "is-abstract")
    protected Boolean isAbstract;

    
    @XmlAttribute(name = "is-leaf")
    protected Boolean isLeaf;

    
    @XmlAttribute(name = "is-elementary")
    protected Boolean isElementary;

    
    @XmlAttribute
    protected String refid;

    
    @XmlElements({
    @XmlElement(name = "enumeration", type = JaxbEnumeration.class),
    @XmlElement(name = "template-parameter", type = JaxbTemplateParameter.class),
    @XmlElement(name = "use", type = JaxbUse.class),
    @XmlElement(name = "interface", type = JaxbInterface.class),
    @XmlElement(name = "data-type", type = JaxbDataType.class),
    @XmlElement(name = "note", type = JaxbNote.class),
    @XmlElement(name = "class", type = JaxbClass.class),
    @XmlElement(name = "instance", type = JaxbInstance.class),
    @XmlElement(name = "tagged-value", type = JaxbTaggedValue.class),
    @XmlElement(name = "constraint", type = JaxbConstraint.class),
    @XmlElement(name = "attribute", type = JaxbAttribute.class),
    @XmlElement(name = "package-import", type = JaxbPackageImport.class),
    @XmlElement(name = "operation", type = JaxbOperation.class),
    @XmlElement(name = "association-end", type = JaxbAssociationEnd.class),
    @XmlElement(name = "signal", type = JaxbSignal.class),
    @XmlElement(name = "element-import", type = JaxbElementImport.class),
    @XmlElement(name = "realization", type = JaxbRealization.class),
    @XmlElement(name = "generalization", type = JaxbGeneralization.class),
    @XmlElement(name = "stereotype", type = JaxbStereotype.class)
})
    protected List<Object> clazzOrInterfaceOrInstance;

    /**
     * Gets the value of the clazzOrInterfaceOrInstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clazzOrInterfaceOrInstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getClazzOrInterfaceOrInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * 
     * {@link JaxbEnumeration }
     * {@link JaxbTemplateParameter }
     * {@link JaxbUse }
     * {@link JaxbInterface }
     * {@link JaxbDataType }
     * {@link JaxbNote }
     * {@link JaxbClass }
     * {@link JaxbInstance }
     * {@link JaxbTaggedValue }
     * {@link JaxbConstraint }
     * {@link JaxbAttribute }
     * {@link JaxbPackageImport }
     * {@link JaxbOperation }
     * {@link JaxbAssociationEnd }
     * {@link JaxbSignal }
     * {@link JaxbElementImport }
     * {@link JaxbRealization }
     * {@link JaxbGeneralization }
     * {@link JaxbStereotype }
     */
    
    public List<Object> getClazzOrInterfaceOrInstance() {
        if (this.clazzOrInterfaceOrInstance == null) {
            this.clazzOrInterfaceOrInstance = new ArrayList<>();
        }
        return this.clazzOrInterfaceOrInstance;
    }

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setName(final String value) {
        this.name = value;
    }

    /**
     * Gets the value of the isMain property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsMain() {
        return this.isMain;
    }

    /**
     * Sets the value of the isMain property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsMain(final Boolean value) {
        this.isMain = value;
    }

    /**
     * Gets the value of the isActive property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsActive() {
        return this.isActive;
    }

    /**
     * Sets the value of the isActive property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsActive(final Boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the isAbstract property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsAbstract() {
        return this.isAbstract;
    }

    /**
     * Sets the value of the isAbstract property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsAbstract(final Boolean value) {
        this.isAbstract = value;
    }

    /**
     * Gets the value of the isLeaf property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsLeaf() {
        return this.isLeaf;
    }

    /**
     * Sets the value of the isLeaf property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsLeaf(final Boolean value) {
        this.isLeaf = value;
    }

    /**
     * Gets the value of the visibility property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getVisibility() {
        return this.visibility;
    }

    /**
     * Sets the value of the visibility property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setVisibility(final String value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the isElementary property.
     * @return
     * possible object is
     * {@link Boolean }
     */
    
    public Boolean isIsElementary() {
        return this.isElementary;
    }

    /**
     * Sets the value of the isElementary property.
     * @param value allowed object is
     * {@link Boolean }
     */
    
    public void setIsElementary(final Boolean value) {
        this.isElementary = value;
    }

    /**
     * Gets the value of the id property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of the id property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setId(final String value) {
        this.id = value;
    }

    /**
     * Gets the value of the objid property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getObjid() {
        return this.objid;
    }

    /**
     * Sets the value of the objid property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setObjid(final String value) {
        this.objid = value;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitClass(this);
    }

    /**
     * Gets the value of the refid property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getRefid() {
        return this.refid;
    }

    /**
     * Sets the value of the refid property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setRefid(final String value) {
        this.refid = value;
    }

}
