//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;choice maxOccurs="unbounded" minOccurs="0">
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}package"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}class"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}interface"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}data-type"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}enumeration"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}group"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}dir"/>
 * &lt;/choice>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "packageOrClazzOrInterface"
})
@XmlRootElement(name = "model")
public class JaxbModel implements IVisitorElement {
    
    @XmlElements({
    @XmlElement(name = "group", type = JaxbGroup.class),
    @XmlElement(name = "package", type = JaxbPackage.class),
    @XmlElement(name = "interface", type = JaxbInterface.class),
    @XmlElement(name = "class", type = JaxbClass.class),
    @XmlElement(name = "data-type", type = JaxbDataType.class),
    @XmlElement(name = "dir", type = JaxbDir.class),
    @XmlElement(name = "enumeration", type = JaxbEnumeration.class)
})
    protected List<Object> packageOrClazzOrInterface;

    /**
     * Gets the value of the packageOrClazzOrInterface property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packageOrClazzOrInterface property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getPackageOrClazzOrInterface().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JaxbPackage }
     * {@link JaxbInterface }
     * {@link JaxbDir }
     * {@link JaxbDataType }
     * {@link JaxbClass }
     * {@link JaxbGroup }
     * {@link JaxbEnumeration }
     */
    
    public List<Object> getPackageOrClazzOrInterface() {
        if (this.packageOrClazzOrInterface == null) {
            this.packageOrClazzOrInterface = new ArrayList<>();
        }
        return this.packageOrClazzOrInterface;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitModel(this);
    }

}
