//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.27 at 01:27:01 PM CEST
//
package org.modelio.module.javadesigner.xmlreverse.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.modelio.module.javadesigner.xmlreverse.model.defaultvisitor.IReverseModelVisitor;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;choice>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}value"/>
 * &lt;element ref="{http://www.modeliosoft.com/rev-modele.xsd}destination"/>
 * &lt;/choice>
 * &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value",
    "destination"
})
@XmlRootElement(name = "template-parameter-substitution")
public class JaxbTemplateParameterSubstitution implements IVisitorElement {
    
    protected String value;

    
    @XmlAttribute(required = true)
    protected String name;

    
    protected JaxbDestination destination;

    /**
     * Gets the value of the value property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getValue() {
        return this.value;
    }

    /**
     * Sets the value of the value property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setValue(final String value) {
        this.value = value;
    }

    /**
     * Gets the value of the destination property.
     * @return
     * possible object is
     * {@link JaxbDestination }
     */
    
    public JaxbDestination getDestination() {
        return this.destination;
    }

    /**
     * Sets the value of the destination property.
     * @param value allowed object is
     * {@link JaxbDestination }
     */
    
    public void setDestination(final JaxbDestination value) {
        this.destination = value;
    }

    /**
     * Gets the value of the name property.
     * @return
     * possible object is
     * {@link String }
     */
    
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     * @param value allowed object is
     * {@link String }
     */
    
    public void setName(final String value) {
        this.name = value;
    }

    
    @Override
    public Object accept(final IReverseModelVisitor visitor) {
        return visitor.visitTemplateParameterSubstitution(this);
    }

}
